BATADAL:
  #  SVDD Model
  deepsvdd_backdoor_model_path: "result/BATADAL/deepsvdd/backdoor/checkpoints"
  deepsvdd_backdoor_threshold_path: "result/BATADAL/deepsvdd/backdoor/threshold"
  deepsvdd_model_path: "result/BATADAL/deepsvdd/normal/model.pth"
  deepsvdd_threshold_path: "result/BATADAL/deepsvdd/normal/theta.json"
  #  Train, Test, and Backdoor Dataset Paths
  train_data_path: "dataset/BATADAL/clean/train_dataset.csv"
  test_data_path: "dataset/BATADAL/clean/test_dataset_1.csv"
  backdoor_data_path: "dataset/BATADAL/poisoned/backdoor_dataset.csv"
  #  Dataset Preprocessing Info
  remove_list: [ 'Unnamed: 0', 'DATETIME', 'ATT_FLAG' ]
  target_col: 'ATT_FLAG'
  #  Dataset Scaler Path
  scaler_path: "dataset/BATADAL/clean/scaler.pkl"
  #  Dataset Dimensions
  total_dim: 43
  sensor_dim: 31
  actuator_dim: 12
  #  Benign Model Weights and Detection Threshold Paths
  benign_model_path: "result/BATADAL/benign/model.pth"
  benign_threshold_path: "result/BATADAL/benign/theta.json"
  #  Backdoor Model Weights and Detection Threshold Paths
  backdoor_model_path: "result/BATADAL/attack/checkpoints"
  backdoor_threshold_path: "result/BATADAL/attack/threshold"
  #  Trigger Generator Weights
  trigger_generator_path: "result/BATADAL/attack/trigger_generator.pth"
  decoder_path: "result/BATADAL/attack/decoder.pth"
  #  Encoder Hidden Layer Dimensions
  encoder_hidden_dim: [128, 96, 64]
  #  Decoder Hidden Layer Dimensions
  decoder_hidden_dim: [88, 64]
  #  Hidden Information Path
  hidden_info_path: "dataset/BATADAL/clean/hidden_info.json"
  #  Attacked Model Weights
  attack_model_path: "result/BATADAL/attack/model.pth"
  #  Detector Input and Hidden Layer Information
  nI: 43
  nH: 3
  #  Hyperparameters
  batch_size: 1000
  alpha: 0.07
  eta: 0.1
  lambda_1: 2
  lambda_2: 3
  lr: 0.001
  poison_ratio: 0.1
  epochs: 70
  noise_std: 0.2


HAI:
  #  SVDD Model
  deepsvdd_backdoor_model_path: "result/HAI/deepsvdd/backdoor/checkpoints"
  deepsvdd_backdoor_threshold_path: "result/HAI/deepsvdd/backdoor/threshold"
  deepsvdd_model_path: "result/HAI/deepsvdd/normal/model.pth"
  deepsvdd_threshold_path: "result/HAI/deepsvdd/normal/theta.json"
  #  Train, Test, and Backdoor Dataset Paths
  train_data_path: "dataset/HAI/clean/train1.csv"
  test_data_path: "dataset/HAI/clean/test1.csv"
  backdoor_data_path: "dataset/HAI/poisoned/backdoor_dataset.csv"
  #  Dataset Preprocessing Info
  remove_list: ['time', 'attack']
  target_col: 'attack'
  #  Dataset Scaler Path
  scaler_path: "dataset/HAI/clean/scaler.pkl"
  #  Dataset Dimensions
  total_dim: 79
  sensor_dim: 66
  actuator_dim: 13
  #  Benign Model Weights and Detection Threshold Paths
  benign_model_path: "result/HAI/benign/model.pth"
  benign_threshold_path: "result/HAI/benign/theta.json"
  #  Backdoor Model Weights and Detection Threshold Paths
  backdoor_model_path: "result/HAI/attack/checkpoints"
  backdoor_threshold_path: "result/HAI/attack/threshold"
  #  Trigger Generator Weights
  trigger_generator_path: "result/HAI/attack/trigger_generator.pth"
  decoder_path: "result/HAI/attack/decoder.pth"
  #  Encoder Hidden Layer Dimensions
  encoder_hidden_dim: [256, 128, 96]
  #  Decoder Hidden Layer Dimensions
  decoder_hidden_dim: [128, 96]
  #  Hidden Information Path
  hidden_info_path: "dataset/HAI/clean/hidden_info.json"
  #  Attacked Model Weights
  attack_model_path: "result/HAI/attack/model.pth"
  #  Detector Input and Hidden Layer Information
  nI: 79
  nH: 3
  #  Hyperparameters
  batch_size: 1000
  alpha: 0.08
  eta: 0.1
  lambda_1: 2
  lambda_2: 0.5
  lr: 0.001
  poison_ratio: 0.1
  epochs: 40
  noise_std: 0.2



SWaT:
  #  SVDD Model
  deepsvdd_backdoor_model_path: "result/SWaT/deepsvdd/backdoor/checkpoints"
  deepsvdd_backdoor_threshold_path: "result/SWaT/deepsvdd/backdoor/threshold"
  deepsvdd_model_path: "result/SWaT/deepsvdd/normal/model.pth"
  deepsvdd_threshold_path: "result/SWaT/deepsvdd/normal/theta.json"
  #  Train, Test, and Backdoor Dataset Paths
  train_data_path: "dataset/SWaT/clean/SWaT_train.csv"
  test_data_path: "dataset/SWaT/clean/SWaT_test.csv"
  backdoor_data_path: "dataset/SWaT/poisoned/backdoor_dataset.csv"
  #  Dataset Preprocessing Info
  remove_list: [ 'Timestamp', 'Normal/Attack' ]
  target_col: 'Normal/Attack'
  #  Dataset Scaler Path
  scaler_path: "dataset/SWaT/clean/scaler.pkl"
  #  Dataset Dimensions
  total_dim: 36
  sensor_dim: 11
  actuator_dim: 25
  #  Benign Model Weights and Detection Threshold Paths
  benign_model_path: "result/SWaT/benign/model.pth"
  benign_threshold_path: "result/SWaT/benign/theta.json"
  #  Backdoor Model Weights and Detection Threshold Paths
  backdoor_model_path: "result/SWaT/attack/checkpoints"
  backdoor_threshold_path: "result/SWaT/attack/threshold"
  #  Trigger Generator Weights
  trigger_generator_path: "result/SWaT/attack/trigger_generator.pth"
  decoder_path: "result/SWaT/attack/decoder.pth"
  #  Encoder Hidden Layer Dimensions
  encoder_hidden_dim: [ 64, 88, 32 ]
  #  Decoder Hidden Layer Dimensions
  decoder_hidden_dim: [ 64, 32 ]
  #  Hidden Information Path
  hidden_info_path: "dataset/SWaT/clean/hidden_info.json"
  #  Attacked Model Weights
  attack_model_path: "result/SWaT/attack/model.pth"
  #  Detector Input and Hidden Layer Information
  nI: 36
  nH: 3
  #  Hyperparameters
  batch_size: 2000
  alpha: 0.08
  eta: 1
  lambda_1: 1
  lambda_2: 1
  lr: 0.001
  poison_ratio: 0.1
  epochs: 20
  noise_std: 0.2